/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/learning_types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Learning Types
         * @description Retrieve set learning types.
         */
        get: operations["get_learning_types_learning_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe endpoint - checks if the application is running.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Readiness probe endpoint.
         *
         *     You might want to add more checks here, such as:
         *     - Database connectivity
         *     - External service dependencies
         *     - Cache availability
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Topics
         * @description Retrieve registered topics.
         */
        get: operations["get_topics_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Models
         * @description Retrieve available LLM models with their health status.
         */
        get: operations["get_models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Modules
         * @description Retrieve modules of the bot.
         */
        get: operations["get_modules_topic__topic__modules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Models Health
         * @description Get the health of the models.
         */
        get: operations["get_models_health_models_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Init Chat */
        post: operations["init_chat_topic__topic__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Invoke */
        post: operations["chat_invoke_topic__topic__message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Title */
        post: operations["update_title_topic__topic__title_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summarize
         * @description Summarize the chat history asynchronously.
         */
        post: operations["summarize_topic__topic__summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/{endpoint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Action Callback */
        post: operations["action_callback_topic__topic___endpoint__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learning_types/from_personality/{personality_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Convert Personality Type
         * @description Convert personality type to learning type.
         */
        get: operations["convert_personality_type_learning_types_from_personality__personality_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/configure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Bots Disabled */
        post: operations["set_bots_disabled_admin_configure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config By Key
         * @description Get the current configuration values using query parameter.
         */
        get: operations["get_config_by_key_admin_config_get"];
        put?: never;
        /**
         * Update Config
         * @description Update the configuration file with new values.
         */
        post: operations["update_config_admin_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AIModelsResponse
         * @description Response model for models with status.
         */
        AIModelsResponse: {
            /** Purposes */
            purposes: components["schemas"]["PurposeModel"][];
            /** Timestamp */
            timestamp: number;
            config: components["schemas"]["ChatConfig"];
            /** Error */
            error?: string | null;
        };
        /**
         * AvailableLearningTypes
         * @description Enumeration of available learning types.
         *
         *     This enum lists all available learning types for the application.
         *
         *     Args:
         *         ...
         *
         *     Returns:
         *         None
         * @enum {string}
         */
        AvailableLearningTypes: "FEELING" | "SENSING" | "INTUITIVE" | "THINKING";
        /**
         * Button
         * @description Represents a button in the chat UI.
         *
         *     This class is used to define a button that can be displayed in the chat
         *     interface, including its label, callback, and optional chat message or state
         *     store.
         *
         *     Args:
         *         label (str): The text displayed on the button.
         *         callback (ButtonCallback): The callback to be triggered when the button
         *             is pressed.
         *         chat_message (Optional[str]): The message to send when the button is pressed.
         *         store (Optional[dict]): State to store when the button is pressed.
         *
         *     Returns:
         *         None
         */
        Button: {
            /** Chat Message */
            chat_message: string;
            /** Label */
            label: string;
            callback: components["schemas"]["ButtonCallback"];
            /**
             * Store
             * @default {}
             */
            store: {
                [key: string]: string;
            };
        };
        /**
         * ButtonCallback
         * @description Represents a callback for a button.
         *
         *     This class defines the callback endpoint and data to be sent when a button
         *     is pressed in the chat UI.
         *
         *     Args:
         *         endpoint (str): The endpoint to call.
         *         data (dict): The data to send to the endpoint.
         *
         *     Returns:
         *         None
         */
        ButtonCallback: {
            /** Endpoint */
            endpoint: string;
            /** Data */
            data: {
                [key: string]: string;
            };
        };
        /**
         * ChatConfig
         * @description Configuration from the backend for the chat in the frontend.
         *
         *     Args:
         *         max_messages_before_summarization (int): The maximum number of messages before
         *             summarization is triggered.
         */
        ChatConfig: {
            /** Max Messages Before Summarization */
            max_messages_before_summarization: number;
        };
        /**
         * ConfigReadResponse
         * @description Response model for reading configuration.
         */
        ConfigReadResponse: {
            /** Success */
            success: boolean;
            /**
             * Error Message
             * @default
             */
            error_message: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ConfigUpdateRequest
         * @description Request model for updating configuration values.
         */
        ConfigUpdateRequest: {
            /** Key */
            key: string;
            /**
             * Updates
             * @description Config values to update
             */
            updates: {
                [key: string]: unknown;
            };
        };
        /**
         * ConfigureTopicsRequest
         * @description Request model for configuring topics.
         */
        ConfigureTopicsRequest: {
            /** Key */
            key: string;
            /** Enabled */
            enabled: {
                [key: string]: boolean;
            };
        };
        /**
         * ConfigureTopicsResponse
         * @description Response model for configuring topics.
         */
        ConfigureTopicsResponse: {
            /** Success */
            success: boolean;
            /**
             * Error Message
             * @default
             */
            error_message: string;
        };
        /**
         * Features
         * @description Features of the bot.
         * @enum {string}
         */
        Features: "title" | "inspirations" | "initiative" | "quiz" | "feedback" | "plan" | "streaming" | "summary" | "aimodel";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail: components["schemas"]["ValidationError"][];
        };
        /**
         * LLM
         * @description Represents a language model (LLM) configuration.
         *
         *     This class is used to represent a language model in the code.
         *
         *     Args:
         *         id (str): The unique identifier for the LLM in LiteLLM.
         *         model_name (str): The base name of the LLM.
         *         label (str): The label of the LLM for endusers.
         *         api_base_url (str): The base URL for the LLM API.
         *         status (LLMStatus): The status of the LLM ('healthy' / 'unhealthy').
         *
         *     Returns:
         *         None
         */
        LLM: {
            /** Id */
            id: string;
            /** Model Name */
            model_name: string;
            /** Label */
            label: string;
            /** Api Base Url */
            api_base_url?: string | null;
            status: components["schemas"]["LLMStatus"];
        };
        /**
         * LLMPurpose
         * @description Purpose of the LLM.
         * @enum {string}
         */
        LLMPurpose: "optimal" | "reasoning" | "german" | "gemini";
        /**
         * LLMStatus
         * @description Status of the LLM.
         * @enum {string}
         */
        LLMStatus: "healthy" | "unhealthy";
        /**
         * LearningTypeModel
         * @description Represents a learning type model.
         *
         *     This class is used to define a learning type, including its ID, name, and
         *     description.
         *
         *     Args:
         *         id (str): The unique identifier for the learning type.
         *         name (str): The name of the learning type.
         *         description (str): The description of the learning type.
         *
         *     Returns:
         *         None
         */
        LearningTypeModel: {
            id: components["schemas"]["AvailableLearningTypes"];
            /** Title */
            title: {
                [key: string]: string;
            };
            /** Short Description */
            short_description: {
                [key: string]: string;
            };
            /** Long Description */
            long_description: {
                [key: string]: string;
            };
        };
        /**
         * LearningTypesResponseModel
         * @description Model for the available learning types.
         */
        LearningTypesResponseModel: {
            /** Learning Types */
            learning_types: components["schemas"]["LearningTypeModel"][];
        };
        /**
         * LocaleType
         * @description Represents supported locale types.
         *
         *     This enum is used to define the supported locales for the application, such as
         *     English and German.
         *
         *     Args:
         *         EN: English locale.
         *         DE: German locale.
         *
         *     Returns:
         *         None
         * @enum {string}
         */
        LocaleType: "en" | "de";
        /**
         * Message
         * @description Represents a single chat message.
         *
         *     This model is used to encapsulate a message exchanged in the chat, including
         *     the sender, content, and optional metadata.
         *
         *     Args:
         *         message (str): The content of the message.
         *         sender (str): The sender of the message (e.g., 'user', 'assistant').
         *         summary (Optional[str]): Optional summary of the message.
         *
         *     Returns:
         *         None
         */
        Message: {
            /** Message */
            message: string;
            sender: components["schemas"]["Sender"];
        };
        /**
         * MessageResponse
         * @description Represents a message response from the bot.
         *
         *     This class is used to encapsulate a message sent by the bot, including the
         *     message content, sender, optional buttons, and meta information.
         *
         *     Args:
         *         message (str): The message content.
         *         sender (Optional[str]): The sender of the message.
         *         buttons (Optional[list[Button]]): List of buttons to display.
         *         meta_information (Optional[MetaInformation]): Additional metadata for
         *             the message.
         *         thoughts (Optional[str]): Optional thoughts or reasoning.
         *
         *     Returns:
         *         None
         */
        MessageResponse: {
            /** Message */
            message: string;
            /** @default assistant */
            sender: components["schemas"]["Sender"];
            /** Thoughts */
            thoughts?: string | null;
            /**
             * Buttons
             * @default []
             */
            buttons: components["schemas"]["Button"][];
            /** @default {} */
            meta_information: components["schemas"]["MetaInformation"];
        };
        /**
         * MetaInformation
         * @description Contains meta information for a message.
         *
         *     This class holds metadata such as sources and the LLM model used for
         *     generating the message.
         *
         *     Args:
         *         sources (Optional[dict[int, Source]]): The sources for the message identified by
         *             an integer id.
         *         llm_model (Optional[str]): The name of the LLM model used.
         *
         *     Returns:
         *         None
         */
        MetaInformation: {
            /** Sources */
            sources: {
                [key: string]: components["schemas"]["Source"];
            };
            /** Citations */
            citations: number[];
            /** Llm Model */
            llm_model: string;
        };
        /**
         * Module
         * @description Represents a simple module of a topic.
         *
         *     This class is used to define a module, including its ID and title.
         *     In contrast to the Skill class, this class does not have multiple levels.
         *
         *     Args:
         *         id (str): The unique identifier for the module.
         *         title (dict): The localized titles for the module.
         *
         *     Returns:
         *         None
         *
         */
        Module: {
            /** Id */
            id: string;
            /** Title */
            title: {
                [key: string]: string;
            };
        };
        /**
         * ModulesResponse
         * @description A Response model for retrieving multiple modules.
         *
         *     This model is used to return a list of modules.
         *
         *     Args:
         *         modules (list[Module]): A list of modules.
         *
         *     Returns:
         *         None
         *
         */
        ModulesResponse: {
            /** Modules */
            modules: components["schemas"]["Module"][];
        };
        /**
         * PersonalityType
         * @description Enumeration of the 16 personality types.
         * @enum {string}
         */
        PersonalityType: "ISTJ" | "ISFJ" | "ESTP" | "ESFP" | "INFJ" | "INTJ" | "ENFP" | "ENTP" | "ISTP" | "INTP" | "ESTJ" | "ENTJ" | "ISFP" | "INFP" | "ESFJ" | "ENFJ";
        /**
         * PersonalityTypeConversionResponse
         * @description Response model for personality type conversion.
         */
        PersonalityTypeConversionResponse: {
            learning_type: components["schemas"]["AvailableLearningTypes"];
        };
        /**
         * PurposeModel
         * @description The selection a user can take to change the model that is used.
         *
         *     Abstracts the difficult LLM names behind a user-friendly label. We decide for the
         *     user which LLM is used for which purpose.
         */
        PurposeModel: {
            id: components["schemas"]["LLMPurpose"];
            /** Label */
            label: {
                [key: string]: string;
            };
            /** Description */
            description: {
                [key: string]: string;
            };
            /** Icon */
            icon: string;
            /** Healthy */
            healthy: boolean;
        };
        /**
         * RequestModel
         * @description Request model for chat and bot endpoints.
         *
         *     This model contains all information sent from the frontend to the backend,
         *     including chat history, user data, and session state.
         *
         *     Args:
         *         learning_type_id (AvailableLearningTypes): The ID of the learning type.
         *         chat_history (list[Message]): The list of previous messages in the conversation.
         *         language (str): The language code for localization.
         *         storage (dict): Key-value store for session-specific data.
         *         streaming (bool): Whether the response should be streamed.
         *         llm (Optional[LLM]): The requested language model.
         *         llm_purpose (Optional[str]): Purpose for which the LLM should be auto-selected.
         *
         *     Returns:
         *         None
         */
        RequestModel: {
            learning_type_id: components["schemas"]["AvailableLearningTypes"];
            /** Language */
            language: string;
            /** Chat History */
            chat_history: (components["schemas"]["Message"] | components["schemas"]["Summary"])[];
            /**
             * Storage
             * @default {}
             */
            storage: {
                [key: string]: string;
            };
            llm?: components["schemas"]["LLM"] | null;
            /** @description The purpose of the LLM to use (e.g., 'optimal' or 'reasoning') */
            llm_purpose?: components["schemas"]["LLMPurpose"] | null;
            /**
             * Streaming
             * @default false
             */
            streaming: boolean;
        };
        /**
         * Response
         * @description Represents a response from the bot.
         *
         *     This class encapsulates a list of message responses to be sent to the frontend.
         *
         *     Args:
         *         messages (list[MessageResponse]): The list of message responses.
         *         storage (Optional[dict[str, str]]): Key-value store for session-specific data.
         *         instructions (Optional[list[str]]): Optional instructions for the frontend.
         *
         *     Returns:
         *         None
         */
        Response: {
            /** Messages */
            messages: components["schemas"]["MessageResponse"][];
            /**
             * Storage
             * @default {}
             */
            storage: {
                [key: string]: string;
            };
            /**
             * Instructions
             * @default []
             */
            instructions: string[];
        };
        /**
         * Sender
         * @description The sender of a message.
         * @enum {string}
         */
        Sender: "assistant" | "user" | "system";
        /**
         * Skill
         * @description Represents a skill of a topic in the learning system.
         *
         *     This class is used to define a skill, including its ID, title, description,
         *     and available levels.
         *
         *     Args:
         *         id (str): The unique identifier for the skill.
         *         title (dict): The localized titles for the skill.
         *         description (dict): The localized descriptions for the skill.
         *         levels (list): The list of levels for the skill.
         *         image (str): The URL of the image representing the skill.
         *
         *     Returns:
         *         None
         */
        Skill: {
            /** Id */
            id: string;
            /** Title */
            title: {
                [key: string]: string;
            };
            /** Levels */
            levels: components["schemas"]["SkillLevel"][];
            /** Description */
            description: {
                [key: string]: string;
            };
            /**
             * Image
             * @default
             */
            image: string;
        };
        /**
         * SkillLevel
         * @description Represents a skill level.
         *
         *     This class is used to define a skill level, including its ID, title,
         *     description, and learning goals.
         *
         *     Args:
         *         id (str): The unique identifier for the skill level.
         *         title (dict): The localized titles for the skill level.
         *         description (dict): The localized descriptions for the skill level.
         *         learning_goals (dict): The localized learning goals for the skill level.
         *
         *     Returns:
         *         None
         */
        SkillLevel: {
            /** Id */
            id: string;
            /** Title */
            title: {
                [key: string]: string;
            };
            /** Description */
            description: {
                [key: string]: string;
            };
            /** Learning Goals */
            learning_goals: {
                [key: string]: string;
            };
        };
        /**
         * Source
         * @description Represents a source document for a message.
         *
         *     This class is used to provide information about the source used for a message,
         *     such as a document or reference.
         *
         *     Args:
         *         title (str): The title of the source.
         *         url (Optional[str]): The URL of the source.
         *         content (Optional[str]): The content of the source.
         *
         *     Returns:
         *         None
         */
        Source: {
            /** Label */
            label: string;
            /** Chunk */
            chunk: string;
            /** Url */
            url: string;
            /**
             * Additional Metadata
             * @default {}
             */
            additional_metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * StatusModel
         * @description Status model.
         */
        StatusModel: {
            /** Status */
            status: string;
        };
        /**
         * Summary
         * @description The format of a summary message.
         */
        Summary: {
            /** Message */
            message: string;
            sender: components["schemas"]["Sender"];
            /** Summary */
            summary: string;
        };
        /**
         * SummaryResponse
         * @description Represents a summary response for a chat session.
         *
         *     This class is used to return a summary of the chat and the number of
         *     messages to keep after summarization.
         *
         *     Args:
         *         summary (str): The summary text.
         *         keep_last_messages_until (int): Number of messages to keep after summarization.
         *
         *     Returns:
         *         None
         */
        SummaryResponse: {
            /** Summary */
            summary: string;
            /** Keep Last Messages Until */
            keep_last_messages_until: number;
        };
        /**
         * TitleResponse
         * @description Represents a title response for a chat session.
         *
         *     This class is used to return a generated title for the chat session.
         *
         *     Args:
         *         title (str): The generated title.
         *
         *     Returns:
         *         None
         */
        TitleResponse: {
            /** Title */
            title: string;
        };
        /**
         * Topic
         * @description Enum of all available topics.
         * @enum {string}
         */
        Topic: "study_competence" | "citation" | "passthrough" | "st";
        /**
         * TopicListModel
         * @description Model representing a collection of topics.
         */
        TopicListModel: {
            /** Topics */
            topics: components["schemas"]["TopicModel"][];
        };
        /**
         * TopicModel
         * @description Model representing a topic in the application.
         */
        TopicModel: {
            endpoint: components["schemas"]["Topic"];
            /** Title */
            title: {
                [key: string]: string;
            };
            /** Short Description */
            short_description: {
                [key: string]: string;
            };
            /** Long Description */
            long_description: {
                [key: string]: string;
            };
            /** Modules */
            modules: (components["schemas"]["Module"] | components["schemas"]["Skill"])[];
            type: components["schemas"]["TopicType"];
            /**
             * Features
             * @default []
             */
            features: components["schemas"]["Features"][];
            /**
             * Color
             * @default #000000
             */
            color: string;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * TopicType
         * @description Enumeration of topic types.
         * @enum {string}
         */
        TopicType: "skills" | "basic";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_learning_types_learning_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningTypesResponseModel"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusModel"];
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_topics_topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicListModel"];
                };
            };
        };
    };
    get_models_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIModelsResponse"];
                };
            };
        };
    };
    get_modules_topic__topic__modules_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic: components["schemas"]["Topic"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModulesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_models_health_models_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    init_chat_topic__topic__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic: components["schemas"]["Topic"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_invoke_topic__topic__message_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic: components["schemas"]["Topic"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_title_topic__topic__title_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic: components["schemas"]["Topic"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summarize_topic__topic__summarize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic: components["schemas"]["Topic"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_callback_topic__topic___endpoint__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic: components["schemas"]["Topic"];
                endpoint: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    convert_personality_type_learning_types_from_personality__personality_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                personality_type: components["schemas"]["PersonalityType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalityTypeConversionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_bots_disabled_admin_configure_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigureTopicsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigureTopicsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_by_key_admin_config_get: {
        parameters: {
            query?: {
                key?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_config_admin_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigureTopicsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
