/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Endpoint that serves Prometheus metrics.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learning_types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Learning Types
         * @description Retrieve set learning types.
         */
        get: operations["get_learning_types_learning_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe endpoint - checks if the application is running.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Readiness probe endpoint.
         *
         *     You might want to add more checks here, such as:
         *     - Database connectivity
         *     - External service dependencies
         *     - Cache availability
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Topics
         * @description Retrieve registered topics.
         */
        get: operations["get_topics_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Models
         * @description Retrieve available LLM models with their health status.
         */
        get: operations["get_models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Modules
         * @description Retrieve modules of the bot.
         */
        get: operations["get_modules_topic__topic__modules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Models Health
         * @description Get the health of the models.
         */
        get: operations["get_models_health_models_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Init Chat */
        post: operations["init_chat_topic__topic__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Invoke */
        post: operations["chat_invoke_topic__topic__message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Title */
        post: operations["update_title_topic__topic__title_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/inspiration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inspiration */
        post: operations["inspiration_topic__topic__inspiration_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/message/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Comment */
        post: operations["comment_topic__topic__message_comment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/message/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vote */
        post: operations["vote_topic__topic__message_vote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Answer Quiz */
        put: operations["answer_quiz_topic__topic__quiz_put"];
        /** Quiz */
        post: operations["quiz_topic__topic__quiz_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/initial_quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initial Quiz */
        post: operations["initial_quiz_topic__topic__initial_quiz_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/answer_initial_quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Initial Quiz */
        post: operations["answer_initial_quiz_topic__topic__answer_initial_quiz_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/quiz/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Quiz Question */
        post: operations["evaluate_quiz_question_topic__topic__quiz_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/quiz/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Quiz */
        post: operations["complete_quiz_topic__topic__quiz_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_topic__topic__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/plan-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Session */
        post: operations["plan_session_topic__topic__plan_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summarize
         * @description Summarize the chat history asynchronously.
         */
        post: operations["summarize_topic__topic__summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topic/{topic}/{endpoint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Action Callback */
        post: operations["action_callback_topic__topic___endpoint__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learning_types/from_personality/{personality_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Convert Personality Type
         * @description Convert personality type to learning type.
         */
        get: operations["convert_personality_type_learning_types_from_personality__personality_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/configure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Bots Disabled */
        post: operations["set_bots_disabled_admin_configure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config By Key
         * @description Get the current configuration values using query parameter.
         */
        get: operations["get_config_by_key_admin_config_get"];
        put?: never;
        /**
         * Update Config
         * @description Update the configuration file with new values.
         */
        post: operations["update_config_admin_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/refresh-scads-bots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Scads Bots
         * @description Refresh ScaDS.AI assistant bots from the external API.
         */
        post: operations["refresh_scads_bots_admin_refresh_scads_bots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/db/schema/drop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Drop Schema */
        get: operations["drop_schema_dev_db_schema_drop_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/db/schema/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Create Schema */
        get: operations["create_schema_dev_db_schema_create_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/db/schema/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Schema */
        get: operations["load_schema_dev_db_schema_load_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/db/data/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Data */
        get: operations["load_data_dev_db_data_load_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/db/schema/valid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schema */
        get: operations["get_schema_dev_db_schema_valid_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/db/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connect Db */
        get: operations["connect_db_dev_db_connect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AIModelsResponse
         * @description Response model for models with status.
         */
        AIModelsResponse: {
            /** Purposes */
            purposes: components["schemas"]["PurposeModel"][];
            /** Timestamp */
            timestamp: number;
            config: components["schemas"]["ChatConfig"];
            /** Error */
            error?: string | null;
        };
        /**
         * AdminRequest
         * @description Base model for admin requests.
         */
        AdminRequest: {
            /** Key */
            key: string;
        };
        /**
         * AvailableLearningTypes
         * @description Enumeration of available learning types.
         *
         *     This enum lists all available learning types for the application.
         *
         *     Args:
         *         ...
         *
         *     Returns:
         *         None
         * @enum {string}
         */
        AvailableLearningTypes: "FEELING" | "SENSING" | "INTUITIVE" | "THINKING";
        /**
         * Button
         * @description Represents a button in the chat UI.
         *
         *     This class is used to define a button that can be displayed in the chat
         *     interface, including its label, callback, and optional chat message or state
         *     store.
         *
         *     Args:
         *         label (str): The text displayed on the button.
         *         callback (ButtonCallback): The callback to be triggered when the button
         *             is pressed.
         *         chat_message (Optional[str]): The message to send when the button is pressed.
         *         store (Optional[dict]): State to store when the button is pressed.
         *
         *     Returns:
         *         None
         */
        Button: {
            /** Chat Message */
            chat_message: string;
            /** Label */
            label: string;
            callback: components["schemas"]["ButtonCallback"];
            /**
             * Store
             * @default {}
             */
            store: {
                [key: string]: string | number | unknown[] | components["schemas"]["LearnerModel-Output"];
            };
        };
        /**
         * ButtonCallback
         * @description Represents a callback for a button.
         *
         *     This class defines the callback endpoint and data to be sent when a button
         *     is pressed in the chat UI.
         *
         *     Args:
         *         endpoint (str): The endpoint to call.
         *         data (dict): The data to send to the endpoint.
         *
         *     Returns:
         *         None
         */
        ButtonCallback: {
            /** Endpoint */
            endpoint: string;
            /** Data */
            data: {
                [key: string]: string;
            };
        };
        /**
         * ChatConfig
         * @description Configuration from the backend for the chat in the frontend.
         *
         *     Args:
         *         max_messages_before_summarization (int): The maximum number of messages before
         *             summarization is triggered.
         */
        ChatConfig: {
            /** Max Messages Before Summarization */
            max_messages_before_summarization: number;
        };
        /**
         * CommentRequestModel
         * @description Request model for adding comments to messages.
         *
         *     Args:
         *         comment (str): The comment to be added to the message.
         *         trace_id (str): The trace ID associated with the message.
         *
         *     Returns:
         *         None
         */
        CommentRequestModel: {
            /** Vote */
            vote: number | null;
            /** Comment */
            comment: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * CommentResponse
         * @description Represents a response for a message comment.
         *
         *     Args:
         *         success (bool): Indicates if the comment was successfully generated.
         *
         *     Returns:
         *         None
         */
        CommentResponse: {
            error?: components["schemas"]["ErrorReport"] | null;
            /** Success */
            success: boolean;
        };
        /**
         * ConfigReadResponse
         * @description Response model for reading configuration.
         */
        ConfigReadResponse: {
            /** Success */
            success: boolean;
            /**
             * Error Message
             * @default
             */
            error_message: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Purposes */
            purposes?: {
                [key: string]: components["schemas"]["PurposeDB"];
            } | null;
        };
        /**
         * ConfigUpdateRequest
         * @description Request model for updating configuration values.
         */
        ConfigUpdateRequest: {
            /** Key */
            key: string;
            /**
             * Updates
             * @description Config values to update
             */
            updates: {
                [key: string]: unknown;
            };
        };
        /**
         * ConfigureTopicsRequest
         * @description Request model for configuring topics.
         */
        ConfigureTopicsRequest: {
            /** Key */
            key: string;
            /** Enabled */
            enabled: {
                [key: string]: boolean;
            };
        };
        /**
         * ConfigureTopicsResponse
         * @description Response model for configuring topics.
         */
        ConfigureTopicsResponse: {
            /** Success */
            success: boolean;
            /**
             * Error Message
             * @default
             */
            error_message: string;
        };
        /** DevResponse */
        DevResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
        };
        /**
         * ErrorReport
         * @description Represents an error report for a chat session.
         *
         *     This class is used to report errors encountered during the chat session,
         *     including the error message and any additional context.
         *
         *     Args:
         *         error (str): The error message.
         *         context (Optional[dict]): Additional context or data related to the error.
         *
         *     Returns:
         *         None
         */
        ErrorReport: {
            /** Error */
            error: string;
            /**
             * Context
             * @default {}
             */
            context: {
                [key: string]: unknown;
            };
        };
        /**
         * Features
         * @description Features of the bot.
         * @enum {string}
         */
        Features: "title" | "inspirations" | "initiative" | "initial_quiz" | "quiz" | "feedback" | "plan" | "streaming" | "summary" | "aimodel" | "scientific_paper_context" | "wip" | "dashboard";
        /**
         * Feedback
         * @description The format of the feedback.
         */
        Feedback: {
            /** Learning Type Rating */
            learning_type_rating: number;
            /** Comment */
            comment: string;
        };
        /**
         * FeedbackRequest
         * @description The format of the feedback request.
         */
        FeedbackRequest: {
            /** Id */
            id: string;
            /** Language */
            language: string;
            /** Chat History */
            chat_history: (components["schemas"]["Message"] | components["schemas"]["Summary"])[];
            /**
             * Storage
             * @default {}
             */
            storage: {
                [key: string]: string | number | unknown[] | {
                    [key: string]: unknown;
                } | components["schemas"]["LearnerModel-Input"];
            };
            /** @description The purpose of the LLM to use (e.g., 'optimal' or 'reasoning') */
            llm_purpose?: components["schemas"]["LLMPurpose"] | null;
            response_preferences: components["schemas"]["ResponsePreferences"];
            /**
             * Streaming
             * @default false
             */
            streaming: boolean;
            feedback: components["schemas"]["Feedback"];
        };
        /**
         * FillInTheBlanksQuestion
         * @description The format for a fill-in-the-blanks question.
         */
        FillInTheBlanksQuestion: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "fill-in-the-blanks";
            /** Score */
            score: [
                number,
                number
            ];
            /** Hint */
            hint: string;
            /** Learning Unit */
            learning_unit: string;
            /**
             * Answered
             * @default false
             */
            answered: boolean;
            /** Feedback */
            feedback?: string | null;
            /** Is Correct */
            is_correct?: boolean | null;
            /** Template */
            template: string;
            /** Solution */
            solution: string[];
            /** Answer */
            answer?: string[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail: components["schemas"]["ValidationError"][];
        };
        /**
         * InitialQuizAnswersRecommendation
         * @description The format of the recommendation based on the initial quiz answers.
         */
        InitialQuizAnswersRecommendation: {
            error?: components["schemas"]["ErrorReport"] | null;
            /** Quiz Performance Below */
            quiz_performance_below: number;
            /** Quiz Performance At Level */
            quiz_performance_at_level: number;
            /** Quiz Performance Above */
            quiz_performance_above: number;
            /** Quiz Recommended Change */
            quiz_recommended_change: number;
        };
        /**
         * InitialQuizAnswersRequest
         * @description The format of the request to submit the answers to the initial quiz.
         */
        InitialQuizAnswersRequest: {
            /** Id */
            id: string;
            /** Language */
            language: string;
            /** Chat History */
            chat_history: (components["schemas"]["Message"] | components["schemas"]["Summary"])[];
            /**
             * Storage
             * @default {}
             */
            storage: {
                [key: string]: string | number | unknown[] | {
                    [key: string]: unknown;
                } | components["schemas"]["LearnerModel-Input"];
            };
            /** @description The purpose of the LLM to use (e.g., 'optimal' or 'reasoning') */
            llm_purpose?: components["schemas"]["LLMPurpose"] | null;
            response_preferences: components["schemas"]["ResponsePreferences"];
            /**
             * Streaming
             * @default false
             */
            streaming: boolean;
            /** Correct Question Ids */
            correct_question_ids: number[];
            /** Questions Asked Per Level */
            questions_asked_per_level: [
                number,
                number,
                number
            ];
        };
        /**
         * InitialQuizModel
         * @description The format of the initial quiz.
         */
        InitialQuizModel: {
            error?: components["schemas"]["ErrorReport"] | null;
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Questions */
            questions: (components["schemas"]["MultipleChoiceQuestion"] | components["schemas"]["SliderQuestion"] | components["schemas"]["TextQuestion"] | components["schemas"]["FillInTheBlanksQuestion"])[];
            /**
             * Completed
             * @default false
             */
            completed: boolean;
            /** Score */
            score: [
                number,
                number
            ];
            /** Quiz Questions Asked Per Level */
            quiz_questions_asked_per_level: [
                number,
                number,
                number
            ];
        };
        /**
         * InspirationsResponse
         * @description The format of the response to get inspirations.
         */
        InspirationsResponse: {
            error?: components["schemas"]["ErrorReport"] | null;
            /** Messages */
            messages: string[];
            /**
             * Storage
             * @default {}
             */
            storage: {
                [key: string]: string;
            };
        };
        /**
         * LLMPurpose
         * @description Purpose of the LLM.
         * @enum {string}
         */
        LLMPurpose: "optimal" | "reasoning" | "german" | "agent" | "agent-thinking-loop" | "agent-strategy-loop";
        /**
         * LearnerModel
         * @description The learner model.
         */
        "LearnerModel-Input": {
            /**
             * Competences
             * @default {}
             */
            competences: {
                [key: string]: components["schemas"]["LearnerModelCompetence-Input"];
            };
            /**
             * Learning Units
             * @default {}
             */
            learning_units: {
                [key: string]: components["schemas"]["LearnerModelLearningUnitInternal"];
            };
        };
        /**
         * LearnerModel
         * @description The learner model.
         */
        "LearnerModel-Output": {
            /**
             * Competences
             * @default {}
             */
            competences: {
                [key: string]: components["schemas"]["LearnerModelCompetence-Output"];
            };
            /**
             * Learning Units
             * @default {}
             */
            learning_units: {
                [key: string]: components["schemas"]["LearnerModelLearningUnitInternal"];
            };
        };
        /**
         * LearnerModelCompetence
         * @description The learner model.
         */
        "LearnerModelCompetence-Input": {
            /** Competence Id */
            competence_id: number;
            /** Competence Code */
            competence_code: string;
            /** Competence Level */
            competence_level: number;
            /**
             * Concepts
             * @default {}
             */
            concepts: {
                [key: string]: components["schemas"]["LearnerModelConcept-Input"];
            };
            /**
             * Name
             * @default {
             *       "en": "Competence",
             *       "de": "Kompetenz"
             *     }
             */
            name: {
                [key: string]: string;
            };
            /**
             * Completed
             * @default false
             */
            completed: boolean;
        };
        /**
         * LearnerModelCompetence
         * @description The learner model.
         */
        "LearnerModelCompetence-Output": {
            /** Competence Id */
            competence_id: number;
            /** Competence Code */
            competence_code: string;
            /** Competence Level */
            competence_level: number;
            /**
             * Concepts
             * @default {}
             */
            concepts: {
                [key: string]: components["schemas"]["LearnerModelConcept-Output"];
            };
            /**
             * Name
             * @default {
             *       "en": "Competence",
             *       "de": "Kompetenz"
             *     }
             */
            name: {
                [key: string]: string;
            };
            /**
             * Completed
             * @default false
             */
            completed: boolean;
        };
        /**
         * LearnerModelConcept
         * @description A competence in the learner model.
         */
        "LearnerModelConcept-Input": {
            /** Concept Id */
            concept_id: number;
            /** Concept Code */
            concept_code: string;
            /**
             * Name
             * @default {
             *       "en": "Concept",
             *       "de": "Konzept"
             *     }
             */
            name: {
                [key: string]: string;
            };
            /**
             * Custom Learning Goals
             * @default
             */
            custom_learning_goals: string;
            /**
             * Learning Units
             * @default {}
             */
            learning_units: {
                [key: string]: components["schemas"]["LearnerModelLearningUnit"];
            };
            /**
             * Completed
             * @default false
             */
            completed: boolean;
        };
        /**
         * LearnerModelConcept
         * @description A competence in the learner model.
         */
        "LearnerModelConcept-Output": {
            /** Concept Id */
            concept_id: number;
            /** Concept Code */
            concept_code: string;
            /**
             * Name
             * @default {
             *       "en": "Concept",
             *       "de": "Konzept"
             *     }
             */
            name: {
                [key: string]: string;
            };
            /**
             * Custom Learning Goals
             * @default
             */
            custom_learning_goals: string;
            /**
             * Learning Units
             * @default {}
             */
            learning_units: {
                [key: string]: components["schemas"]["LearnerModelLearningUnit"];
            };
            /**
             * Completed
             * @default false
             */
            completed: boolean;
        };
        /**
         * LearnerModelLearningUnit
         * @description A learning unit in the learner model.
         */
        LearnerModelLearningUnit: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /**
             * Name
             * @default {
             *       "en": "Unit",
             *       "de": "Einheit"
             *     }
             */
            name: {
                [key: string]: string;
            };
            /**
             * Times Seen
             * @default 0
             */
            times_seen: number;
            /** Last Seen */
            last_seen?: string | null;
            /**
             * Times Quizzed
             * @default 0
             */
            times_quizzed: number;
            /**
             * Times Correct
             * @default 0
             */
            times_correct: number;
            /** Last Quizzed */
            last_quizzed?: string | null;
            /**
             * Completed
             * @default false
             */
            completed: boolean;
        };
        /**
         * LearnerModelLearningUnitInternal
         * @description Internal representation of a learning unit in the learner model.
         */
        LearnerModelLearningUnitInternal: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /**
             * Name
             * @default {
             *       "en": "Unit",
             *       "de": "Einheit"
             *     }
             */
            name: {
                [key: string]: string;
            };
            /**
             * Times Seen
             * @default 0
             */
            times_seen: number;
            /** Last Seen */
            last_seen?: string | null;
            /**
             * Times Quizzed
             * @default 0
             */
            times_quizzed: number;
            /**
             * Times Correct
             * @default 0
             */
            times_correct: number;
            /** Last Quizzed */
            last_quizzed?: string | null;
            /**
             * Completed
             * @default false
             */
            completed: boolean;
            /** Competence Code */
            competence_code: string;
            /** Concept Code */
            concept_code: string;
        };
        /**
         * LearningTypeModel
         * @description Represents a learning type model.
         *
         *     This class is used to define a learning type, including its ID, name, and
         *     description.
         *
         *     Args:
         *         id (str): The unique identifier for the learning type.
         *         name (str): The name of the learning type.
         *         description (str): The description of the learning type.
         *
         *     Returns:
         *         None
         */
        LearningTypeModel: {
            id: components["schemas"]["AvailableLearningTypes"];
            /** Title */
            title: {
                [key: string]: string;
            };
            /** Short Description */
            short_description: {
                [key: string]: string;
            };
            /** Long Description */
            long_description: {
                [key: string]: string;
            };
        };
        /**
         * LearningTypesResponseModel
         * @description Model for the available learning types.
         */
        LearningTypesResponseModel: {
            /** Learning Types */
            learning_types: components["schemas"]["LearningTypeModel"][];
        };
        /**
         * LocaleType
         * @description Represents supported locale types.
         *
         *     This enum is used to define the supported locales for the application, such as
         *     English and German.
         *
         *     Args:
         *         EN: English locale.
         *         DE: German locale.
         *
         *     Returns:
         *         None
         * @enum {string}
         */
        LocaleType: "en" | "de";
        /**
         * Message
         * @description Represents a single chat message.
         *
         *     This model is used to encapsulate a message exchanged in the chat, including
         *     the sender, content, and optional metadata.
         *
         *     Args:
         *         content (str): The content of the message.
         *         type (str): The sender of the message (e.g., 'user', 'assistant').
         *         summary (Optional[str]): Optional summary of the message.
         *
         *     Returns:
         *         None
         */
        Message: {
            /** Content */
            content: string;
            type: components["schemas"]["MessageType"];
            /** Timestamp */
            timestamp: string;
        };
        /**
         * MessageResponse
         * @description Represents a message response from the bot.
         *
         *     This class is used to encapsulate a message sent by the bot, including the
         *     message content, sender, optional buttons, and meta information.
         *
         *     Args:
         *         content (str): The message content.
         *         type (Optional[str]): The sender of the message.
         *         buttons (Optional[list[Button]]): List of buttons to display.
         *         meta_information (Optional[MetaInformation]): Additional metadata for
         *             the message.
         *         thoughts (Optional[str]): Optional thoughts or reasoning.
         *
         *     Returns:
         *         None
         */
        MessageResponse: {
            /** Content */
            content: string;
            /** @default assistant */
            type: components["schemas"]["MessageType"];
            /** Thoughts */
            thoughts?: string | null;
            /**
             * Buttons
             * @default []
             */
            buttons: components["schemas"]["Button"][];
            /** @default {} */
            meta_information: components["schemas"]["MetaInformation"];
        };
        /**
         * MessageType
         * @description The sender of a message.
         * @enum {string}
         */
        MessageType: "assistant" | "user" | "system";
        /**
         * MessageVoteRequest
         * @description Request model for voting on messages.
         *
         *     Args:
         *         vote (int): The vote value, typically 1 for upvote and -1 for downvote.
         *         trace_id (str): The trace ID associated with the message.
         *
         *     Returns:
         *         None
         */
        MessageVoteRequest: {
            /** Vote */
            vote: number;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * MessageVoteResponse
         * @description Represents a response for a message vote.
         *
         *     This class is used to indicate whether the vote operation was successful.
         *
         *     Args:
         *         success (bool): Indicates if the vote was successfully recorded.
         *
         *     Returns:
         *         None
         */
        MessageVoteResponse: {
            error?: components["schemas"]["ErrorReport"] | null;
            /** Success */
            success: boolean;
        };
        /**
         * MetaInformation
         * @description Contains meta information for a message.
         *
         *     This class holds metadata such as sources and the LLM model used for
         *     generating the message.
         *
         *     Args:
         *         sources (Optional[dict[int, Source]]): The sources for the message identified by
         *             an integer id.
         *         llm_model (Optional[str]): The name of the LLM model used.
         *
         *     Returns:
         *         None
         */
        MetaInformation: {
            /** Sources */
            sources: {
                [key: string]: components["schemas"]["Source"];
            };
            /** Citations */
            citations: number[];
            /** Llm Model */
            llm_model: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Module
         * @description Represents a simple module of a topic.
         *
         *     This class is used to define a module, including its ID and title.
         *     In contrast to the Skill class, this class does not have multiple levels.
         *
         *     Args:
         *         id (int): The unique identifier for the module.
         *         code (str): The code of the module, typically used for identification.
         *         title (dict): The localized titles for the module.
         *
         *     Returns:
         *         None
         *
         */
        Module: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Title */
            title: {
                [key: string]: string;
            };
        };
        /**
         * ModulesResponse
         * @description A Response model for retrieving multiple modules.
         *
         *     This model is used to return a list of modules.
         *
         *     Args:
         *         modules (list[Module]): A list of modules.
         *
         *     Returns:
         *         None
         *
         */
        ModulesResponse: {
            /** Modules */
            modules: components["schemas"]["Module"][];
        };
        /**
         * MultipleChoiceQuestion
         * @description The format for a multiple-choice question.
         */
        MultipleChoiceQuestion: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "multiple-choice";
            /** Score */
            score: [
                number,
                number
            ];
            /** Hint */
            hint: string;
            /** Learning Unit */
            learning_unit: string;
            /**
             * Answered
             * @default false
             */
            answered: boolean;
            /** Feedback */
            feedback?: string | null;
            /** Is Correct */
            is_correct?: boolean | null;
            /** Options */
            options: string[];
            /** Solution */
            solution: number[];
            /** Answer */
            answer?: number[] | null;
        };
        /**
         * PersonalityType
         * @description Enumeration of the 16 personality types.
         * @enum {string}
         */
        PersonalityType: "ISTJ" | "ISFJ" | "ESTP" | "ESFP" | "INFJ" | "INTJ" | "ENFP" | "ENTP" | "ISTP" | "INTP" | "ESTJ" | "ENTJ" | "ISFP" | "INFP" | "ESFJ" | "ENFJ";
        /**
         * PersonalityTypeConversionResponse
         * @description Response model for personality type conversion.
         */
        PersonalityTypeConversionResponse: {
            learning_type: components["schemas"]["AvailableLearningTypes"];
        };
        /**
         * PlanResponse
         * @description The format of the response to plan the next session.
         */
        PlanResponse: {
            error?: components["schemas"]["ErrorReport"] | null;
            /** Recommended Topics */
            recommended_topics: string[];
            /** Recommended Date */
            recommended_date: string;
            /**
             * Storage
             * @default {}
             */
            storage: {
                [key: string]: string;
            };
        };
        /**
         * PurposeDB
         * @description DB model for LLM purposes.
         */
        PurposeDB: {
            /** Idpurposes */
            idpurposes: number;
            /** Code */
            code: string;
            /** Icon */
            icon?: string | null;
            /** Models */
            models: string[];
            /** Enabled */
            enabled: boolean;
        };
        /**
         * PurposeModel
         * @description The selection a user can take to change the model that is used.
         *
         *     Abstracts the difficult LLM names behind a user-friendly label. We decide for the
         *     user which LLM is used for which purpose.
         */
        PurposeModel: {
            id: components["schemas"]["LLMPurpose"];
            /** Label */
            label: {
                [key: string]: string;
            };
            /** Description */
            description: {
                [key: string]: string;
            };
            /** Icon */
            icon: string;
            /** Healthy */
            healthy: boolean;
        };
        /**
         * QuizAnswers
         * @description The format of the request to submit the answers to the test.
         */
        QuizAnswers: {
            /** Question Id */
            question_id: number;
            /** Selected Options Ids */
            selected_options_ids: number[];
        };
        /**
         * QuizAnswersRequest
         * @description The format of the request to submit the answers to the test.
         */
        QuizAnswersRequest: {
            /** Id */
            id: string;
            /** Language */
            language: string;
            /** Chat History */
            chat_history: (components["schemas"]["Message"] | components["schemas"]["Summary"])[];
            /**
             * Storage
             * @default {}
             */
            storage: {
                [key: string]: string | number | unknown[] | {
                    [key: string]: unknown;
                } | components["schemas"]["LearnerModel-Input"];
            };
            /** @description The purpose of the LLM to use (e.g., 'optimal' or 'reasoning') */
            llm_purpose?: components["schemas"]["LLMPurpose"] | null;
            response_preferences: components["schemas"]["ResponsePreferences"];
            /**
             * Streaming
             * @default false
             */
            streaming: boolean;
            /** Questions */
            questions: (components["schemas"]["MultipleChoiceQuestion"] | components["schemas"]["SliderQuestion"] | components["schemas"]["TextQuestion"] | components["schemas"]["FillInTheBlanksQuestion"])[];
            /** Answers */
            answers: components["schemas"]["QuizAnswers"][];
        };
        /**
         * QuizCompletionRequest
         * @description The format of the request to complete the quiz.
         */
        QuizCompletionRequest: {
            /** Id */
            id: string;
            /** Language */
            language: string;
            /** Chat History */
            chat_history: (components["schemas"]["Message"] | components["schemas"]["Summary"])[];
            /**
             * Storage
             * @default {}
             */
            storage: {
                [key: string]: string | number | unknown[] | {
                    [key: string]: unknown;
                } | components["schemas"]["LearnerModel-Input"];
            };
            /** @description The purpose of the LLM to use (e.g., 'optimal' or 'reasoning') */
            llm_purpose?: components["schemas"]["LLMPurpose"] | null;
            response_preferences: components["schemas"]["ResponsePreferences"];
            /**
             * Streaming
             * @default false
             */
            streaming: boolean;
            quiz: components["schemas"]["QuizModel"];
        };
        /**
         * QuizCompletionResponse
         * @description The format of the response for completing the quiz.
         */
        QuizCompletionResponse: {
            error?: components["schemas"]["ErrorReport"] | null;
            /** Messages */
            messages: components["schemas"]["MessageResponse"][];
            /**
             * Storage
             * @default {}
             */
            storage: {
                [key: string]: string | number | unknown[] | components["schemas"]["LearnerModel-Output"];
            };
            /**
             * Instructions
             * @default []
             */
            instructions: string[];
            /** Events */
            events: {
                [key: string]: unknown;
            }[];
        };
        /**
         * QuizModel
         * @description The format of the quiz, now supporting multiple question types.
         */
        QuizModel: {
            error?: components["schemas"]["ErrorReport"] | null;
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Questions */
            questions: (components["schemas"]["MultipleChoiceQuestion"] | components["schemas"]["SliderQuestion"] | components["schemas"]["TextQuestion"] | components["schemas"]["FillInTheBlanksQuestion"])[];
            /**
             * Completed
             * @default false
             */
            completed: boolean;
            /** Score */
            score: [
                number,
                number
            ];
        };
        /**
         * QuizQuestionEvaluationRequest
         * @description The format of the request to evaluate a single quiz question answer.
         */
        QuizQuestionEvaluationRequest: {
            /** Id */
            id: string;
            /** Language */
            language: string;
            /** Chat History */
            chat_history: (components["schemas"]["Message"] | components["schemas"]["Summary"])[];
            /**
             * Storage
             * @default {}
             */
            storage: {
                [key: string]: string | number | unknown[] | {
                    [key: string]: unknown;
                } | components["schemas"]["LearnerModel-Input"];
            };
            /** @description The purpose of the LLM to use (e.g., 'optimal' or 'reasoning') */
            llm_purpose?: components["schemas"]["LLMPurpose"] | null;
            response_preferences: components["schemas"]["ResponsePreferences"];
            /**
             * Streaming
             * @default false
             */
            streaming: boolean;
            /** Question */
            question: components["schemas"]["MultipleChoiceQuestion"] | components["schemas"]["SliderQuestion"] | components["schemas"]["TextQuestion"] | components["schemas"]["FillInTheBlanksQuestion"];
            /** User Answer */
            user_answer: string | number | string[] | number[];
        };
        /**
         * QuizQuestionEvaluationResponse
         * @description The format of the response for a single quiz question evaluation.
         */
        QuizQuestionEvaluationResponse: {
            error?: components["schemas"]["ErrorReport"] | null;
            /** Score */
            score: number;
            /** Max Score */
            max_score: number;
            /** Is Correct */
            is_correct: boolean;
            /** Solution */
            solution: string | number | string[] | number[];
            /** Feedback */
            feedback: string;
            /**
             * Storage
             * @default {}
             */
            storage: {
                [key: string]: string;
            };
        };
        /**
         * RefreshScadsBotsResponse
         * @description Response model for refreshing ScaDS bots.
         */
        RefreshScadsBotsResponse: {
            /** Success */
            success: boolean;
            /**
             * Error Message
             * @default
             */
            error_message: string;
            /**
             * Bots Added
             * @default []
             */
            bots_added: string[];
            /**
             * Bots Removed
             * @default []
             */
            bots_removed: string[];
            /**
             * Total Bots
             * @default 0
             */
            total_bots: number;
        };
        /**
         * RequestModel
         * @description Request model for chat and bot endpoints.
         *
         *     This model contains all information sent from the frontend to the backend,
         *     including chat history, user data, and session state.
         *
         *     Args:
         *         id (str): The unique identifier for the request, typically msg timestamp.
         *         chat_history (list[Message]): The list of previous messages in the conversation.
         *         language (str): The language code for localization.
         *         storage (dict): Key-value store for session-specific data.
         *         streaming (bool): Whether the response should be streamed.
         *         response_preferences (ResponsePreferences):
         *             How the user wants the response to be tailored.
         *         llm_purpose (Optional[str]): Purpose for which the LLM should be auto-selected.
         *
         *     Returns:
         *         None
         */
        RequestModel: {
            /** Id */
            id: string;
            /** Language */
            language: string;
            /** Chat History */
            chat_history: (components["schemas"]["Message"] | components["schemas"]["Summary"])[];
            /**
             * Storage
             * @default {}
             */
            storage: {
                [key: string]: string | number | unknown[] | {
                    [key: string]: unknown;
                } | components["schemas"]["LearnerModel-Input"];
            };
            /** @description The purpose of the LLM to use (e.g., 'optimal' or 'reasoning') */
            llm_purpose?: components["schemas"]["LLMPurpose"] | null;
            response_preferences: components["schemas"]["ResponsePreferences"];
            /**
             * Streaming
             * @default false
             */
            streaming: boolean;
        };
        /**
         * Response
         * @description Represents a response from the bot.
         *
         *     This class encapsulates a list of message responses to be sent to the frontend.
         *
         *     Args:
         *         messages (list[MessageResponse]): The list of message responses.
         *         storage (Optional[dict[str, str]]): Key-value store for session-specific data.
         *         instructions (Optional[list[str]]): Optional instructions for the frontend.
         *
         *     Returns:
         *         None
         */
        Response: {
            error?: components["schemas"]["ErrorReport"] | null;
            /** Messages */
            messages: components["schemas"]["MessageResponse"][];
            /**
             * Storage
             * @default {}
             */
            storage: {
                [key: string]: string | number | unknown[] | components["schemas"]["LearnerModel-Output"];
            };
            /**
             * Instructions
             * @default []
             */
            instructions: string[];
        };
        /**
         * ResponsePreferences
         * @description The desired preferences for the response message.
         *
         *     Each value must be an integer from 0 to 4, where 2 is the neutral default.
         */
        ResponsePreferences: {
            /** Detail */
            detail: number;
            /** Illustration */
            illustration: number;
            /** Language Style */
            language_style: number;
            /** Humour */
            humour: number;
            /** Creativity */
            creativity: number;
            /** Emojis */
            emojis: number;
        };
        /**
         * Skill
         * @description Represents a skill of a topic in the learning system.
         *
         *     This class is used to define a skill, including its ID, title, description,
         *     and available levels.
         *
         *     Args:
         *         id (str): The unique identifier for the skill.
         *         title (dict): The localized titles for the skill.
         *         description (dict): The localized descriptions for the skill.
         *         levels (list): The list of levels for the skill.
         *         image (str): The URL of the image representing the skill.
         *
         *     Returns:
         *         None
         */
        Skill: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Title */
            title: {
                [key: string]: string;
            };
            /** Levels */
            levels: components["schemas"]["SkillLevel"][];
            /** Description */
            description: {
                [key: string]: string;
            };
            /**
             * Image
             * @default
             */
            image: string;
        };
        /**
         * SkillLevel
         * @description Represents a skill level.
         *
         *     This class is used to define a skill level, including its ID, title,
         *     description, and learning goals.
         *
         *     Args:
         *         id (int): The unique identifier for the skill level.
         *         code (str): The code of the skill level, typically used for identification.
         *         title (dict): The localized titles for the skill level.
         *         description (dict): The localized descriptions for the skill level.
         *         learning_goals (dict): The localized learning goals for the skill level.
         *
         *     Returns:
         *         None
         */
        SkillLevel: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Title */
            title: {
                [key: string]: string;
            };
            /** Description */
            description: {
                [key: string]: string;
            };
            /** Learning Goals */
            learning_goals: {
                [key: string]: string;
            };
        };
        /**
         * SliderQuestion
         * @description The format for a slider question.
         */
        SliderQuestion: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "slider";
            /** Score */
            score: [
                number,
                number
            ];
            /** Hint */
            hint: string;
            /** Learning Unit */
            learning_unit: string;
            /**
             * Answered
             * @default false
             */
            answered: boolean;
            /** Feedback */
            feedback?: string | null;
            /** Is Correct */
            is_correct?: boolean | null;
            /** Min */
            min: number;
            /** Max */
            max: number;
            /** Step */
            step: number;
            /** Solution */
            solution: number;
            /** Answer */
            answer?: number | null;
        };
        /**
         * Source
         * @description Represents a source document for a message.
         *
         *     This class is used to provide information about the source used for a message,
         *     such as a document or reference.
         *
         *     Args:
         *         title (str): The title of the source.
         *         url (Optional[str]): The URL of the source.
         *         content (Optional[str]): The content of the source.
         *
         *     Returns:
         *         None
         */
        Source: {
            /** Title */
            title: string;
            /** Chunk */
            chunk: string;
            /** Thumbnail */
            thumbnail?: string | null;
            /** Year */
            year?: number | null;
            /**
             * Authors
             * @default []
             */
            authors: string[];
            original_language?: components["schemas"]["LocaleType"] | null;
            /**
             * Additional Metadata
             * @default {}
             */
            additional_metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * StatusModel
         * @description Status model.
         */
        StatusModel: {
            /** Status */
            status: string;
        };
        /**
         * Summary
         * @description The format of a summary message.
         */
        Summary: {
            /** Content */
            content: string;
            type: components["schemas"]["MessageType"];
            /** Timestamp */
            timestamp: string;
            /** Summary */
            summary: string;
        };
        /**
         * SummaryResponse
         * @description Represents a summary response for a chat session.
         *
         *     This class is used to return a summary of the chat and the number of
         *     messages to keep after summarization.
         *
         *     Args:
         *         summary (str): The summary text.
         *         keep_last_messages_until (int): Number of messages to keep after summarization.
         *
         *     Returns:
         *         None
         */
        SummaryResponse: {
            error?: components["schemas"]["ErrorReport"] | null;
            /** Summary */
            summary: string;
            /** Keep Last Messages Until */
            keep_last_messages_until: number;
        };
        /**
         * TextQuestion
         * @description The format for a free-text question.
         */
        TextQuestion: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "free-text";
            /** Score */
            score: [
                number,
                number
            ];
            /** Hint */
            hint: string;
            /** Learning Unit */
            learning_unit: string;
            /**
             * Answered
             * @default false
             */
            answered: boolean;
            /** Feedback */
            feedback?: string | null;
            /** Is Correct */
            is_correct?: boolean | null;
            /** Placeholder */
            placeholder: string;
            /** Solution */
            solution: string;
            /** Answer */
            answer?: string | null;
        };
        /**
         * TitleResponse
         * @description Represents a title response for a chat session.
         *
         *     This class is used to return a generated title for the chat session.
         *
         *     Args:
         *         title (str): The generated title.
         *
         *     Returns:
         *         None
         */
        TitleResponse: {
            error?: components["schemas"]["ErrorReport"] | null;
            /** Title */
            title: string;
        };
        /**
         * TopicListModel
         * @description Model representing a collection of topics.
         */
        TopicListModel: {
            /** Topics */
            topics: components["schemas"]["TopicModel"][];
        };
        /**
         * TopicModel
         * @description Model representing a topic in the application.
         */
        TopicModel: {
            /** Endpoint */
            endpoint: string;
            /** Title */
            title: {
                [key: string]: string;
            };
            /** Short Description */
            short_description: {
                [key: string]: string;
            };
            /** Long Description */
            long_description: {
                [key: string]: string;
            };
            /** Modules */
            modules: (components["schemas"]["Module"] | components["schemas"]["Skill"])[];
            type: components["schemas"]["TopicType"];
            /**
             * Features
             * @default []
             */
            features: components["schemas"]["Features"][];
            /**
             * Color
             * @default #000000
             */
            color: string;
            /** Avatar */
            avatar?: string | null;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /**
             * Optional
             * @default true
             */
            optional: boolean;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Tag */
            tag?: string | null;
        };
        /**
         * TopicType
         * @description Enumeration of topic types.
         * @enum {string}
         */
        TopicType: "skills" | "basic" | "coach";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_learning_types_learning_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningTypesResponseModel"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusModel"];
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_topics_topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicListModel"];
                };
            };
        };
    };
    get_models_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIModelsResponse"];
                };
            };
        };
    };
    get_modules_topic__topic__modules_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModulesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_models_health_models_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    init_chat_topic__topic__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_invoke_topic__topic__message_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_title_topic__topic__title_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspiration_topic__topic__inspiration_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspirationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    comment_topic__topic__message_comment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentRequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vote_topic__topic__message_vote_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageVoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageVoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_quiz_topic__topic__quiz_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizAnswersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quiz_topic__topic__quiz_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    initial_quiz_topic__topic__initial_quiz_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitialQuizModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_initial_quiz_topic__topic__answer_initial_quiz_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitialQuizAnswersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitialQuizAnswersRecommendation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_quiz_question_topic__topic__quiz_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizQuestionEvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizQuestionEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_quiz_topic__topic__quiz_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizCompletionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizCompletionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_topic__topic__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_session_topic__topic__plan_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summarize_topic__topic__summarize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_callback_topic__topic___endpoint__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpoint: string;
                /** @description Bot topic identifier */
                topic: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    convert_personality_type_learning_types_from_personality__personality_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                personality_type: components["schemas"]["PersonalityType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalityTypeConversionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_bots_disabled_admin_configure_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigureTopicsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigureTopicsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_by_key_admin_config_get: {
        parameters: {
            query?: {
                key?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_config_admin_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigureTopicsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_scads_bots_admin_refresh_scads_bots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshScadsBotsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drop_schema_dev_db_schema_drop_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevResponse"];
                };
            };
        };
    };
    create_schema_dev_db_schema_create_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevResponse"];
                };
            };
        };
    };
    load_schema_dev_db_schema_load_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevResponse"];
                };
            };
        };
    };
    load_data_dev_db_data_load_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevResponse"];
                };
            };
        };
    };
    get_schema_dev_db_schema_valid_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevResponse"];
                };
            };
        };
    };
    connect_db_dev_db_connect_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevResponse"];
                };
            };
        };
    };
}
